### ISSUE TITLE
restart Buffer Saver without restarting PostgreSQL server

### ISSUE THREAD

**Issue by kotsachin** [gurjeet/pg_hibernator#6]
Hi,

I am planning to use pg_hibernator tool developed by you.

Tu dump in memory data using pg_hibernator we are killing Buffer Saver process , which dumps all in memory connect to pg_hibernator directory.

Now problem we are facing is , we want Buffer Saver come up without restarting server.
Is it possible to start killed (kill {pid}) Buffer Saver process bring back without restarting server?

If you know any trick to do that please let me know as soon as possible.

**Comment by gurjeet** [comment]
Hi @kotsachin I investigated the possibility of saving the buffer list withut killing the BGWorker process, but unfortunately that doesn't seem to be possible with the current code.

It may be possible by registering a custom signal handler in the worker. Please feel free to contribute such a feature.
